---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Merging CopyKit Objects

CopyKit objects can be merged into one object with the `cbind()` function.

Example:
```{r}
# gain of chromosome 7 and deletion of chromosome 10
ck1 <- mock_bincounts(
  ncells = 50,
  ncells_diploid = 0,
  position_gain = 4900:5493,
  position_del = 6523:7056,
  genome = "hg38",
  resolution = "220kb"
)


# adding an identifier to colData
colData(ck1)$info <- 'object1'
```

```{r}
# gain of chromosome 7 and deletion of chromosome 10
# additional gain of chromosome 1
ck2 <- mock_bincounts(
  ncells = 50,
  ncells_diploid = 0,
  position_gain = c(1:906, 4900:5493),
  position_del = 6523:7056,
  genome = "hg38",
  resolution = "220kb"
)

# adding an identifier to colData
colData(ck2)$info <- 'object2'
```

```{r}
# merging objects
merged_copykit <- cbind(ck1, ck2)
```


Following merge a standard CopyKit analysis can be applied


```{r}
# UMAP and clustering
merged_copykit <- runUmap(merged_copykit)
merged_copykit <- findSuggestedK(merged_copykit)
merged_copykit <- findClusters(merged_copykit)

plotUmap(merged_copykit, label = 'subclones')

# plotting
plotHeatmap(merged_copykit, label = 'info', order_cells = 'hclust')
```




